name: front_office
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dotted_line: ^3.1.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_local_notifications: ^14.0.0+1
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.18.0
  open_street_map_search_and_pick: ^0.0.16
  table_calendar: ^3.0.9
  flutter_datetime_picker: ^1.5.1
  timezone: ^0.9.2
  cupertino_icons: ^1.0.5
  mailer: ^6.0.1
  slack_notifier: ^1.2.0
  file_picker: ^5.3.0
  http_parser: ^4.0.2
  mime: ^1.0.4




dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
